### ISSUE TITLE
Getting some minnor errors with systemui

### ISSUE THREAD

**Issue by Gontier-Julien** [Evolution-X-AOSP/frameworks_base#332]
I'm getting some error with systemui when it start up, nothing serious tho, but i guess it was good for me to report them.
It doesn't crash anything, but at least it preferable in my opinion that i report them to prevent any potential bugs ^^

Latest version of Oneplus8 Android 13 09/19/2022

https://pastebin.com/Mu1qmw4f

https://pastebin.com/mzzZ8WJ8

**Comment by joeyhuab** [comment]
> I'm getting some error with systemui when it start up, nothing serious tho, but i guess it was good for me to report them. It doesn't crash anything, but at least it preferable in my opinion that i report them to prevent any potential bugs ^^
> 
> Latest version of Oneplus8 Android 13 09/19/2022
> 
> [pastebin.com/Mu1qmw4f](https://pastebin.com/Mu1qmw4f)
> 
> [pastebin.com/mzzZ8WJ8](https://pastebin.com/mzzZ8WJ8)

The first error has been explained multiple times that wiping package cache won't work for a new lib like that which causes that error, which is why we required a clean flash in the first place.

Never seen the 2nd error either so yeah kindly do the recommended instructions instead of always trying to dirty flash.
